version: '1'

services:
  nginx:
    image: nginx:latest
    container_name: glu-nginx-container
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - testingnetwork

  php-fpm:
    build: ./docker/php7
    container_name: glu-php-container
    links:
      - mysql
      - redis
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOSTNAME=mysql
      - DB_DATABASE=rfilipov
      - DB_USERNAME=root
      - DB_PASSWORD=root

    volumes:
      - ./:/var/www/html
    networks:
      - testingnetwork

  redis:
    image: redis:4.0.5-alpine
    ports:
      - 63790:6379
    hostname: redis
    networks:
      - testingnetwork
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rfilipov
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD:root
    networks:
      - testingnetwork
    volumes:
      - my-data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql

networks:
  testingnetwork:
    external:
      name: testingnetwork

volumes:
  redis-data:  
  my-data:
